create database if not exists school;
use school;
set sql_safe_updates=0;
drop table if exists students;
create table students(USN varchar(10),s_name varchar(10));
alter table students add(class char(1),percentage decimal(4,1),marks numeric(3,0),result boolean);
alter table students modify USN varchar(5) not null;
alter table students drop percentage;
insert into students(USN,s_name,class,marks,result) values ("WN232","Rohan A","U",98,null);
insert into students(USN,s_name,class,marks,result) values ("WN233","Rohan B","U",70,null);
insert into students(USN,s_name,class,marks,result) values ("WN234","Rohan C","U",88,null);
insert into students(USN,s_name,class,marks,result) values ("WN235","Rohan D","U",32,null);
update students set result=true where marks>=35;
update students set result=false where marks<35;
set sql_safe_updates=1;
select * from students;
select s_name from students;
select * from students order by marks desc;
select USN,s_name from students where result=true order by marks desc;